/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface ConnectPayload {
  url: string
  urls: Array<string>
  user: string
  pwd: string
}

export interface LatestText {
  text: string
  contentId: string
}

export interface NativeClipboardContent {
  kind: string
  text: string
  contentId: string
  dataName: string
  data: Uint8Array
}

export interface NativeCreateSpaceResult {
  spaceId: string
  selfDeviceId: string
}

export interface NativeHistoryItem {
  id: string
  text: string
  kind: string
  timestampMs: number
  starred: boolean
  pinned: boolean
  hasData: boolean
  version: number
}

export interface NativeJoinSpaceResult {
  spaceId: string
  sponsorDeviceId: string
  selfDeviceId: string
}

export interface NativeMobileSyncCredential {
  deviceId: string
  label: string
  username: string
  password: string
  connectUri: string
  urls: Array<string>
}

export interface NativeMobileSyncDevice {
  deviceId: string
  label: string
  username: string
  online: boolean
  createdAtMs: number
  lastSeenAtMs: number
  lastSeenIp: string
}

export interface NativeMobileSyncInboundEvent {
  kind: string
  text: string
  dataName: string
  mimeType: string
  data: Uint8Array
  contentId: string
  sourceLabel: string
}

export interface NativeMobileSyncStatus {
  enabled: boolean
  lanListenEnabled: boolean
  running: boolean
  port: number
  urls: Array<string>
}

export interface NativeServerConfig {
  baseUrl: string
  username: string
  password: string
}

export interface NativeSpaceDevice {
  deviceId: string
  deviceName: string
  deviceType: string
  isLocal: boolean
  online: boolean
  state: string
  channel: string
}

export interface NativeSpaceFileEvent {
  data: Uint8Array
  fileName: string
  fromDeviceId: string
  snapshotHash: string
  localPath: string
  fileSize: number
}

export interface NativeSpaceFileSendResult {
  acceptedCount: number
  transferId: string
}

export interface NativeSpaceFileStatusEvent {
  transferId: string
  status: string
  reason: string
}

export interface NativeSpaceImageEvent {
  data: Uint8Array
  mimeType: string
  fromDeviceId: string
  snapshotHash: string
}

export interface NativeSpaceInvitation {
  code: string
  expiresAtMs: number
}

export interface NativeSpaceMemberSyncPreferences {
  sendEnabled: boolean
  text: boolean
  image: boolean
  file: boolean
  link: boolean
  richText: boolean
}

export interface NativeSpaceStatus {
  running: boolean
  joined: boolean
  deviceName: string
  spaceId: string
}

export interface NativeSpaceTextEvent {
  text: string
  fromDeviceId: string
  snapshotHash: string
}

export interface NativeSseEvent {
  eventType: string
  detail: string
}

/**
  * Actively dial one paired space device instead of waiting for the periodic
  * keepalive pass. Returns true only when the core reports the peer online.
  */
export declare function connectSpaceDevice(deviceId: string): Promise<boolean>

/** Stream a materialized received file into an open HarmonyOS save target. */
export declare function copySpaceFileToFd(sourcePath: string, targetFd: number): Promise<void>

/**
  * Initialize a new encrypted UniClipboard space on this device. Invitation
  * issuance is intentionally a separate action so the owner can retry or
  * refresh a code without attempting to initialize the space again.
  */
export declare function createSpace(passphrase: string, deviceName: string): Promise<NativeCreateSpaceResult>

export declare function deleteHistory(config: NativeServerConfig, kind: string, hash: string, version: number): Promise<NativeHistoryItem>

export declare function deleteTextHistory(config: NativeServerConfig, hash: string, version: number): Promise<NativeHistoryItem>

export declare function drainMobileSyncInboundEvents(): Array<NativeMobileSyncInboundEvent>

/** Drain file clipboard frames received from peers since the previous call. */
export declare function drainSpaceFileEvents(): Array<NativeSpaceFileEvent>

/** Drain sender-side status changes reported by the receiving peer. */
export declare function drainSpaceFileStatusEvents(): Array<NativeSpaceFileStatusEvent>

/** Drain image clipboard frames received from peers since the previous call. */
export declare function drainSpaceImageEvents(): Array<NativeSpaceImageEvent>

/** Drain text clipboard frames received from peers since the previous call. */
export declare function drainSpaceTextEvents(): Array<NativeSpaceTextEvent>

export declare function drainSseEvents(): Array<NativeSseEvent>

export declare function getHistoryPayload(config: NativeServerConfig, kind: string, hash: string): Promise<Uint8Array>

export declare function getLatestContent(config: NativeServerConfig): Promise<NativeClipboardContent>

export declare function getLatestText(config: NativeServerConfig): Promise<LatestText>

/** Return persisted mobile-sync settings plus the actual in-process listener state. */
export declare function getMobileSyncServerStatus(): Promise<NativeMobileSyncStatus>

/**
  * Return the persisted member roster enriched with live reachability and the
  * HarmonyOS device type announced by each peer through the encrypted space.
  */
export declare function getSpaceDevices(): Promise<Array<NativeSpaceDevice>>

/** Return the local device's outbound sync preferences for one paired member. */
export declare function getSpaceMemberSyncPreferences(deviceId: string): Promise<NativeSpaceMemberSyncPreferences>

export declare function getSpaceStatus(): Promise<NativeSpaceStatus>

/** Issue a fresh, short-lived invitation for the space owned by this device. */
export declare function issueSpaceInvitation(): Promise<NativeSpaceInvitation>

export declare function joinSpace(invitationCode: string, passphrase: string, deviceName: string): Promise<NativeJoinSpaceResult>

export declare function listMobileSyncDevices(): Promise<Array<NativeMobileSyncDevice>>

export declare function parseConnectUri(uri: string): ConnectPayload

export declare function probeServer(config: NativeServerConfig): Promise<void>

export declare function publishMobileSyncFileFromFd(fd: number, fileSize: number, fileName: string, mimeType: string): string

export declare function publishMobileSyncImage(data: Uint8Array, mimeType: string): string

export declare function publishMobileSyncText(text: string): string

/**
  * Upload a user-selected file to the configured desktop mobile-sync endpoint
  * and activate it there. The descriptor remains owned by ArkTS; this bridge
  * only reads it through `/proc/self/fd/<n>` while the async call is pending.
  */
export declare function putFileFromFd(config: NativeServerConfig, fd: number, fileSize: number, fileName: string): Promise<string | null>

export declare function putImage(config: NativeServerConfig, data: Uint8Array): Promise<string | null>

export declare function putText(config: NativeServerConfig, text: string): Promise<string | null>

export declare function queryClipboardHistory(config: NativeServerConfig, page: number, searchText: string, starredOnly: boolean): Promise<Array<NativeHistoryItem>>

export declare function queryTextHistory(config: NativeServerConfig, page: number, searchText: string, starredOnly: boolean): Promise<Array<NativeHistoryItem>>

/** Create long-lived Basic Auth credentials and the official UniClipboard connect URI. */
export declare function registerMobileSyncDevice(label: string, customUsername: string, customPassword: string, port: number): Promise<NativeMobileSyncCredential>

/**
  * Replace the currently active space with a newly self-owned space without
  * uninstalling the application. Old peer membership/trust records are
  * removed before the new owner record is created.
  */
export declare function replaceSpace(passphrase: string, deviceName: string): Promise<NativeCreateSpaceResult>

/** Restore both outbound and inbound preferences for one member to defaults. */
export declare function resetSpaceMemberSyncPreferences(deviceId: string): Promise<NativeSpaceMemberSyncPreferences>

export declare function revokeMobileSyncDevice(deviceId: string): Promise<void>

/**
  * Remove a paired device from the current space. The target device will be
  * evicted from the member roster, its peer address cache, and the trusted
  * peer table so it must re-pair to rejoin.
  */
export declare function revokeSpaceMember(deviceId: string): Promise<void>

/** Dispatch one user-selected file through the joined encrypted space in bounded chunks. */
export declare function sendSpaceFile(data: Uint8Array, fileName: string): Promise<number>

export declare function sendSpaceFileFromFd(fd: number, fileSize: number, fileName: string): Promise<NativeSpaceFileSendResult>

export declare function sendSpaceFileFromFdToDevice(fd: number, fileSize: number, fileName: string, deviceId: string): Promise<NativeSpaceFileSendResult>

export declare function sendSpaceImage(data: Uint8Array, mimeType: string): Promise<number>

export declare function sendSpaceImageToDevice(data: Uint8Array, mimeType: string, deviceId: string): Promise<number>

export declare function sendSpaceText(text: string): Promise<number>

export declare function sendSpaceTextToDevice(text: string, deviceId: string): Promise<number>

export declare function setHistoryPinned(config: NativeServerConfig, kind: string, hash: string, pinned: boolean, version: number): Promise<NativeHistoryItem>

export declare function setHistoryStarred(config: NativeServerConfig, kind: string, hash: string, starred: boolean, version: number): Promise<NativeHistoryItem>

/** Enable/disable the embedded SyncClipboard-compatible LAN HTTP server. */
export declare function setMobileSyncServerEnabled(enabled: boolean, port: number): Promise<NativeMobileSyncStatus>

/**
  * Enable or disable the stricter background connection monitor. While a
  * HarmonyOS long-running task is active, cached peer connections are
  * revalidated every 15 seconds so lock-screen network suspension cannot
  * leave the application silently attached to a dead QUIC connection.
  */
export declare function setSpaceBackgroundMode(active: boolean): void

export declare function setTextHistoryPinned(config: NativeServerConfig, hash: string, pinned: boolean, version: number): Promise<NativeHistoryItem>

export declare function setTextHistoryStarred(config: NativeServerConfig, hash: string, starred: boolean, version: number): Promise<NativeHistoryItem>

export declare function sha256HexUpper(text: string): string

/**
  * Start the embedded UniClipboard P2P node inside the HarmonyOS application
  * sandbox. This must be called once before redeeming a space invitation.
  */
export declare function startSpaceNode(dataDir: string, cacheDir: string, deviceType: string): Promise<NativeSpaceStatus>

export declare function startSse(config: NativeServerConfig): void

export declare function stopSpaceNode(): Promise<void>

export declare function stopSse(): void

/**
  * Switch an already configured device to another encrypted space. Local
  * clipboard history is preserved by the application layer's crash-safe
  * re-encryption migration; the invitation must be issued by a member of the
  * target space.
  */
export declare function switchSpace(invitationCode: string, newPassphrase: string): Promise<NativeJoinSpaceResult>

/**
  * Update all outbound controls shown by the HarmonyOS device details page.
  * The unexposed code-snippet and all receive-side preferences are preserved.
  */
export declare function updateSpaceMemberSendPreferences(deviceId: string, sendEnabled: boolean, text: boolean, image: boolean, file: boolean, link: boolean, richText: boolean): Promise<NativeSpaceMemberSyncPreferences>

/**
  * Wake the native peer scheduler and force-revalidate cached connections.
  * HarmonyOS calls this after returning to the foreground so a connection
  * invalidated by lock-screen network suspension is redialed immediately
  * instead of waiting for the 30-second fast-path TTL or QUIC idle timeout.
  */
export declare function wakeSpaceConnections(): void
