/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface ConnectPayload {
  url: string
  urls: Array<string>
  user: string
  pwd: string
}

export interface LatestText {
  text: string
  contentId: string
}

export interface NativeClipboardContent {
  kind: string
  text: string
  contentId: string
  dataName: string
  data: Uint8Array
}

export interface NativeCreateSpaceResult {
  spaceId: string
  selfDeviceId: string
}

export interface NativeHistoryItem {
  id: string
  text: string
  kind: string
  timestampMs: number
  starred: boolean
  pinned: boolean
  hasData: boolean
  version: number
}

export interface NativeJoinSpaceResult {
  spaceId: string
  sponsorDeviceId: string
  selfDeviceId: string
}

export interface NativeServerConfig {
  baseUrl: string
  username: string
  password: string
}

export interface NativeSpaceDevice {
  deviceId: string
  deviceName: string
  deviceType: string
  isLocal: boolean
  online: boolean
  state: string
}

export interface NativeSpaceFileEvent {
  data: Uint8Array
  fileName: string
  fromDeviceId: string
  snapshotHash: string
  localPath: string
  fileSize: number
}

export interface NativeSpaceFileSendResult {
  acceptedCount: number
  transferId: string
}

export interface NativeSpaceFileStatusEvent {
  transferId: string
  status: string
  reason: string
}

export interface NativeSpaceImageEvent {
  data: Uint8Array
  mimeType: string
  fromDeviceId: string
  snapshotHash: string
}

export interface NativeSpaceInvitation {
  code: string
  expiresAtMs: number
}

export interface NativeSpaceStatus {
  running: boolean
  joined: boolean
  deviceName: string
  spaceId: string
}

export interface NativeSpaceTextEvent {
  text: string
  fromDeviceId: string
  snapshotHash: string
}

export interface NativeSseEvent {
  eventType: string
  detail: string
}

/**
  * Actively dial one paired space device instead of waiting for the periodic
  * keepalive pass. Returns true only when the core reports the peer online.
  */
export declare function connectSpaceDevice(deviceId: string): Promise<boolean>

/** Stream a materialized received file into an open HarmonyOS save target. */
export declare function copySpaceFileToFd(sourcePath: string, targetFd: number): Promise<void>

/**
  * Initialize a new encrypted UniClipboard space on this device. Invitation
  * issuance is intentionally a separate action so the owner can retry or
  * refresh a code without attempting to initialize the space again.
  */
export declare function createSpace(passphrase: string, deviceName: string): Promise<NativeCreateSpaceResult>

export declare function deleteTextHistory(config: NativeServerConfig, hash: string, version: number): Promise<NativeHistoryItem>

/** Drain file clipboard frames received from peers since the previous call. */
export declare function drainSpaceFileEvents(): Array<NativeSpaceFileEvent>

/** Drain sender-side status changes reported by the receiving peer. */
export declare function drainSpaceFileStatusEvents(): Array<NativeSpaceFileStatusEvent>

/** Drain image clipboard frames received from peers since the previous call. */
export declare function drainSpaceImageEvents(): Array<NativeSpaceImageEvent>

/** Drain text clipboard frames received from peers since the previous call. */
export declare function drainSpaceTextEvents(): Array<NativeSpaceTextEvent>

export declare function drainSseEvents(): Array<NativeSseEvent>

export declare function getLatestContent(config: NativeServerConfig): Promise<NativeClipboardContent>

export declare function getLatestText(config: NativeServerConfig): Promise<LatestText>

/**
  * Return the persisted member roster enriched with live reachability and the
  * HarmonyOS device type announced by each peer through the encrypted space.
  */
export declare function getSpaceDevices(): Promise<Array<NativeSpaceDevice>>

export declare function getSpaceStatus(): Promise<NativeSpaceStatus>

/** Issue a fresh, short-lived invitation for the space owned by this device. */
export declare function issueSpaceInvitation(): Promise<NativeSpaceInvitation>

export declare function joinSpace(invitationCode: string, passphrase: string, deviceName: string): Promise<NativeJoinSpaceResult>

export declare function parseConnectUri(uri: string): ConnectPayload

export declare function probeServer(config: NativeServerConfig): Promise<void>

export declare function putImage(config: NativeServerConfig, data: Uint8Array): Promise<string | null>

export declare function putText(config: NativeServerConfig, text: string): Promise<string | null>

export declare function queryTextHistory(config: NativeServerConfig, page: number, searchText: string, starredOnly: boolean): Promise<Array<NativeHistoryItem>>

/** Dispatch one user-selected file through the joined encrypted space in bounded chunks. */
export declare function sendSpaceFile(data: Uint8Array, fileName: string): Promise<number>

/**
  * Publish a user-selected file through iroh-blobs using its open HarmonyOS
  * file descriptor.  The descriptor remains owned by ArkTS and is never
  * closed here; `/proc/self/fd/<n>` lets iroh stream/copy it without loading
  * the full file into memory.
  */
export declare function sendSpaceFileFromFd(fd: number, fileSize: number, fileName: string): Promise<NativeSpaceFileSendResult>

/**
  * Dispatch a compressed image through the joined UniClipboard space. The
  * HarmonyOS layer keeps this payload below the encrypted wire inline limit.
  */
export declare function sendSpaceImage(data: Uint8Array, mimeType: string): Promise<number>

/**
  * Dispatch UTF-8 text through the joined UniClipboard space. The return
  * value is the number of online peers that accepted the encrypted frame.
  */
export declare function sendSpaceText(text: string): Promise<number>

export declare function setTextHistoryPinned(config: NativeServerConfig, hash: string, pinned: boolean, version: number): Promise<NativeHistoryItem>

export declare function setTextHistoryStarred(config: NativeServerConfig, hash: string, starred: boolean, version: number): Promise<NativeHistoryItem>

export declare function sha256HexUpper(text: string): string

/**
  * Start the embedded UniClipboard P2P node inside the HarmonyOS application
  * sandbox. This must be called once before redeeming a space invitation.
  */
export declare function startSpaceNode(dataDir: string, cacheDir: string, deviceType: string): Promise<NativeSpaceStatus>

export declare function startSse(config: NativeServerConfig): void

export declare function stopSpaceNode(): Promise<void>

export declare function stopSse(): void

/**
  * Wake the native peer scheduler immediately, for example when the
  * HarmonyOS ability returns to the foreground or network access resumes.
  */
export declare function wakeSpaceConnections(): void
