[workspace]
members = [
  "crates/uc-content-hash",
  "crates/uc-core",
  "crates/uc-app-paths",
  "crates/uc-observability",
  "crates/uc-mobile-proto",
  "crates/uc-infra",
  "crates/uc-application",
  "crates/uc-platform",
  "crates/uc-bootstrap",
]
resolver = "2"

[workspace.package]
version = "0.19.0-alpha.3"
license = "AGPL-3.0-only"

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
print_stdout = "warn"
print_stderr = "warn"
dbg_macro = "warn"

[profile.release]
panic = "abort"
codegen-units = 1
lto = "thin"
opt-level = "z"
strip = "symbols"
